# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rweather.proto\"\x10\n\x0eWeatherRequest\"\'\n\x0fWeatherResponse\x12\x14\n\x0cjson_message\x18\x01 \x01(\t2@\n\x08Reporter\x12\x34\n\rWeatherReport\x12\x0f.WeatherRequest\x1a\x10.WeatherResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEATHERREQUEST = _descriptor.Descriptor(
  name='WeatherRequest',
  full_name='WeatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=33,
)


_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_message', full_name='WeatherResponse.json_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['WeatherRequest'] = _WEATHERREQUEST
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERREQUEST,
  __module__ = 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherRequest)
  ))
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERRESPONSE,
  __module__ = 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherResponse)
  ))
_sym_db.RegisterMessage(WeatherResponse)


# @@protoc_insertion_point(module_scope)
