# Generated by Django 4.1.4 on 2022-12-10 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
