name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
      - name: Deploy to production
        if: success()
        run: |
          docker-compose pull
          docker-compose up -d

