name: Docker-Compose CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test 
      run: |
        docker-compose build 
        docker-compose up
        docker-compose down