name: Docker-Compose CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Fix Docker-compose problems
      run: |
        sudo usermod -aG docker ec2-user
        sudo ./svc.sh stop
        sudo ./svc.sh start

    - name: Build and Test
      run: |
        docker-compose down
        docker-compose build

    - name: Running the project
      run: docker-compose up -d
