name: Docker-Compose CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    

    - name: Build and Test
      run: |
        sudo systemctl restart docker
        docker system prune -a
        docker-compose down
        docker-compose build

    - name: Running the project
      run: docker-compose up -d
